src/main/java/org/nlpcn/jcoder/domain/ApiDoc.java
package org.nlpcn.jcoder.domain;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public abstract class ApiDoc {

	private String name;
	private String content;
	protected List<ApiDoc> sub;
	protected Map<String, String> attr;

	public ApiDoc(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public List<ApiDoc> getSub() {
		return sub;
	}

	public void setSub(List<ApiDoc> sub) {
		this.sub = sub;
	}

	public Map<String, String> getAttr() {
		return attr;
	}

	public void setAttr(Map<String, String> attr) {
		this.attr = attr;
	}

	public void addAttr(String key, String value) {
		if (this.attr == null) {
			this.attr = new HashMap<>();
		}
		attr.put(key, value);
	}

	public abstract ApiDoc createSubDoc(String name);

}

src/main/java/org/nlpcn/jcoder/domain/ClassDoc.java
package org.nlpcn.jcoder.domain;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * api 的信息类
 * 
 * @author ansj
 *
 */

public class ClassDoc extends ApiDoc {

	public ClassDoc(String name) {
		super(name);
	}

	private boolean single = true;

	private boolean status = true;
	
	private String version ;

	private String description;

	public boolean isSingle() {
		return single;
	}

	public void setSingle(boolean single) {
		this.single = single;
	}
	
	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public class MethodDoc extends ApiDoc {
		public MethodDoc(String name) {
			super(name);
		}

		private boolean defaultExecute;

		private String retrunContent;

		private Set<String> methods = new HashSet<>();
		
		public boolean isDefaultExecute() {
			return defaultExecute;
		}

		public void setDefaultExecute(boolean defaultExecute) {
			this.defaultExecute = defaultExecute;
		}

		public String getRetrunContent() {
			return retrunContent;
		}

		public void setRetrunContent(String retrunContent) {
			this.retrunContent = retrunContent;
		}

		public Set<String> getMethods() {
			return methods;
		}

		public void setMethods(Set<String> methods) {
			this.methods = methods;
		}

		public void addMethod(String method) {
			methods.add(method);
		}

		public class ParamDoc extends ApiDoc {

			private String fieldName;

			private String type;

			public ParamDoc(String name) {
				super(name);
			}

			public String getFieldName() {
				return fieldName;
			}

			public void setFieldName(String fieldName) {
				this.fieldName = fieldName;
			}

			public String getType() {
				return type;
			}

			public void setType(String type) {
				this.type = type;
			}

			@Override
			public ApiDoc createSubDoc(String name) {
				return null;
			}
		}

		@Override
		public ApiDoc createSubDoc(String name) {
			ParamDoc paramDoc = new ParamDoc(name);
			if (sub == null) {
				sub = new ArrayList<>();
			}
			sub.add(paramDoc);
			return paramDoc;
		}
	}

	@Override
	public ApiDoc createSubDoc(String name) {
		MethodDoc methodDoc = new MethodDoc(name);
		if (sub == null) {
			sub = new ArrayList<>();
		}
		sub.add(methodDoc);
		return methodDoc;
	}

}

src/main/java/org/nlpcn/jcoder/domain/FileInfo.java
package org.nlpcn.jcoder.domain;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Date;

import org.nlpcn.commons.lang.util.StringUtil;

public class FileInfo implements Comparable<FileInfo> {

	private File file;

	private String name;

	public FileInfo(File file) {
		this.file = file;
	}

	public FileInfo(File file, String name) {
		this.file = file;
		this.name = name;
	}

	public String getName() {
		if (StringUtil.isBlank(name)) {
			return file.getName();
		}
		return name;
	}

	public File getFile() {
		return file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getEncodingPath() throws UnsupportedEncodingException {
		return URLEncoder.encode(file.getAbsolutePath(), "utf-8");
	}

	@Override
	public int hashCode() {
		return this.file.hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof JarInfo) {
			return this.file.getAbsolutePath().equals(((JarInfo) obj).getFile().getAbsolutePath());
		} else {
			return false;
		}
	}

	public Date getDate() {
		return new Date(file.lastModified());
	}

	@Override
	public int compareTo(FileInfo ji) {
		return (this.file.getAbsolutePath().compareTo(ji.file.getAbsolutePath()));
	}
}

src/main/java/org/nlpcn/jcoder/domain/Group.java
package org.nlpcn.jcoder.domain;

import org.nutz.dao.entity.annotation.Column;
import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Table;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Table("groups")
public class Group {

    @Id
    private Long id;

    @Column
    private String name;

    @Column
    private String description;

    @Column("create_time")
    private Date createTime;
    
    
    private List<Map<String,Object>> users; 

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    

    public List<Map<String, Object>> getUsers() {
		return users;
	}

	public void setUsers(List<Map<String, Object>> users) {
		this.users = users;
	}

	@Override
    public String toString() {
	return "Group [id=" + id + ", name=" + name + ", description="
		+ description + ", createTime=" + createTime + "]";
    }
}

src/main/java/org/nlpcn/jcoder/domain/JarInfo.java
package org.nlpcn.jcoder.domain;

import java.io.File;

import org.nlpcn.jcoder.service.JarService;

public class JarInfo extends FileInfo {

	private int status; // 0 加载成功 1 未加载 2 未释放

	public JarInfo(File file, int status) {
		super(file);
		this.status = status;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean getIsMavenJar() {
		return this.getFile().getParentFile().equals(new File(JarService.JAR_PATH + "/target/dependency/"));
	}
}

src/main/java/org/nlpcn/jcoder/controller/ApiAction.java
package org.nlpcn.jcoder.controller;

import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import org.nlpcn.jcoder.domain.ClassDoc;
import org.nlpcn.jcoder.domain.ClassDoc.MethodDoc;
import org.nlpcn.jcoder.domain.CodeInfo.ExecuteMethod;
import org.nlpcn.jcoder.domain.Task;
import org.nlpcn.jcoder.filter.AuthoritiesManager;
import org.nlpcn.jcoder.run.java.JavaRunner;
import org.nlpcn.jcoder.run.java.JavaSourceUtil;
import org.nlpcn.jcoder.scheduler.ThreadManager;
import org.nlpcn.jcoder.service.TaskService;
import org.nlpcn.jcoder.util.ExceptionUtil;
import org.nlpcn.jcoder.util.JavaDocUtil;
import org.nlpcn.jcoder.util.Restful;
import org.nlpcn.jcoder.util.StaticValue;
import org.nutz.ioc.loader.annotation.Inject;
import org.nutz.ioc.loader.annotation.IocBean;
import org.nutz.mvc.Mvcs;
import org.nutz.mvc.annotation.At;
import org.nutz.mvc.annotation.By;
import org.nutz.mvc.annotation.Filters;
import org.nutz.mvc.annotation.Ok;
import org.nutz.mvc.annotation.Param;
import org.nutz.mvc.filter.CrossOriginFilter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.alibaba.fastjson.JSONObject;
import com.google.common.collect.Sets;

@IocBean
public class ApiAction {

	private static final Logger LOG = LoggerFactory.getLogger(ApiAction.class);

	private static final Set<String> DEFAULT_METHODS = Sets.newHashSet("GET", "POST", "PUT", "DELETE");

	@Inject
	private TaskService taskService;

	/**
	 * api
	 * 
	 * @return api info
	 */
	@At("/apidoc/info")
	@Ok("json")
	@Filters(@By(type = CrossOriginFilter.class))
	public Object api(@Param(value = "type", df = "1") int type) {

		List<ClassDoc> result = TaskService.findTaskList(type).stream().sorted((t1, t2) -> {
			int v = (int) (t1.getGroupId() - t2.getGroupId());
			if (v != 0) {
				return v;
			}
			return (int) (t1.getId() - t2.getId());
		}).map((t) -> {
			boolean compile = false;
			ClassDoc cd = null;
			try {
				new JavaRunner(t).compile();
				compile = true;
			} catch (Exception e1) {
				LOG.error(e1.getMessage(), e1);
			}
			try {
				cd = JavaDocUtil.parse(new StringReader(t.getCode()));
				cd.getSub().stream().forEach(method -> {
					ExecuteMethod executeMethod = t.codeInfo().getExecuteMethod(method.getName());
					MethodDoc md = (MethodDoc) method;
					if (executeMethod.isRestful()) {
						if (executeMethod.getMethodTypeSet().size() == 0) {
							md.getMethods().addAll(DEFAULT_METHODS);
						} else {
							md.getMethods().addAll(executeMethod.getMethodTypeSet());
						}
					}
					if (executeMethod.isRpc()) {
						md.addMethod("RPC");
					}

				});

			} catch (Exception e) {
				e.printStackTrace();
				cd = new ClassDoc(t.getName());
			}
			cd.setStatus(compile);
			cd.setVersion(t.getVersion());
			cd.setDescription(t.getDescription());
			return cd;
		}).collect(Collectors.toList());

		return result;

	}

	/**
	 * 执行测试用户的api
	 * 
	 * @param jsonTask
	 * @return
	 */
	@At("/run_api")
	@Ok("raw")
	@Filters(@By(type = AuthoritiesManager.class, args = { "userType", "1", "/login.jsp" }))
	public Object runApi(@Param("json") String jsonTask) {

		String taskName = null;
		try {

			JSONObject json = JSONObject.parseObject(jsonTask);

			String code = json.getString("task.code");
			String codeType = json.getString("task.codeType");

			Task task = new Task();
			task.setCode(code);
			task.setCodeType(codeType);
			task.setType(2);

			taskName = task.getName() + "@" + "0@" + Mvcs.getReq().getRemoteAddr();

			if (ThreadManager.checkActionExists(taskName)) {
				LOG.warn(taskName + " has beening run! pleast stop it first!");
			} else {
				LOG.info(taskName + " publish ok ! will be run !");
				ThreadManager.add2ActionTask(taskName, Thread.currentThread());
				LOG.info(taskName + " result : " + new JavaRunner(task).compile().instance().execute());
			}

		} catch (Exception e) {
			e.printStackTrace();
			LOG.error(taskName + " " + ExceptionUtil.printStackTraceWithOutLine(e));

			return StaticValue.errMessage(e.getMessage());
		} finally {
			if (taskName != null)
				ThreadManager.removeActionIfOver(taskName);
		}

		return StaticValue.okMessage("code run over!");
	}

	/**
	 * 停止一个api任务
	 * 
	 * @param jsonTask
	 * @return
	 */
	@At("/stop_api")
	@Ok("raw")
	@Filters(@By(type = AuthoritiesManager.class, args = { "userType", "1", "/login.jsp" }))
	public Object stopApi(@Param("json") String jsonTask) {

		String taskName = null;
		try {
			JSONObject json = JSONObject.parseObject(jsonTask);
			taskName = JavaSourceUtil.findClassName(json.getString("task.code")) + "@" + "0@" + Mvcs.getReq().getRemoteAddr();
			LOG.info(taskName + " will be to stop ! ");
			ThreadManager.stop(taskName);
			LOG.info(taskName + " stoped ! ");
			return StaticValue.OK;
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error(taskName + " err " + ExceptionUtil.printStackTraceWithOutLine(e));
			return StaticValue.ERR;
		}
	}

	/**
	 * 查看api的不同
	 * 
	 * @param jsonTask
	 * @return
	 * @throws UnsupportedEncodingException
	 */
	@At("/api_diff")
	@Ok("json")
	public Object diff(String name, String code) throws UnsupportedEncodingException {

		Task task = TaskService.findTaskByCache(name);

		if (task == null) {
			return Restful.instance(false, "notFound");
		}

		code = code.replace("\r", "");
		String tCode = task.getCode().replaceAll("\r", "");

		if (code.trim().equals(tCode.trim())) {
			return Restful.instance(true, "same");
		}

		Date updateTime = task.getUpdateTime();

		return Restful.instance(false, "unSame", updateTime);

	}

}

src/main/java/org/nlpcn/jcoder/controller/ConsoleAction.java
package org.nlpcn.jcoder.controller;

import java.util.concurrent.ConcurrentHashMap;

import javax.websocket.CloseReason;
import javax.websocket.Endpoint;
import javax.websocket.EndpointConfig;
import javax.websocket.OnClose;
import javax.websocket.OnError;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.ServerEndpoint;

import org.nlpcn.jcoder.util.websocket.WebSocketConfigurator;
import org.nutz.ioc.loader.annotation.IocBean;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ServerEndpoint(value = "/console", configurator = WebSocketConfigurator.class)
@IocBean(create = "init", depose = "depose")
public class ConsoleAction extends Endpoint {

	protected static final Logger LOG = LoggerFactory.getLogger(ConsoleAction.class);

	protected ConcurrentHashMap<String, Session> sessions = new ConcurrentHashMap<>();

	public void init() {
		LOG.info("websocket service starting");
	}

	/**
	 * send all message for online client
	 * 
	 * @param message
	 */
	public void sendMessage(final String message) {
		sessions.entrySet().parallelStream().forEach(e -> {
			Session session = e.getValue();
			if (session.isOpen()) {
				session.getAsyncRemote().sendText(message);
			}
		});
	}


	@OnClose
	public void onClose(Session session, CloseReason closeReason) {
		sessions.remove(session.getId());
	}

	@OnError
	public void onError(Session session, java.lang.Throwable throwable) {
		onClose(session, null);
	}

	@OnOpen
	public void onOpen(Session session, EndpointConfig config) {
		sessions.put(session.getId(), session);
	}

	@OnMessage
	public void onMessage(String message, Session session) {
		LOG.info(session.getId() + ":" + message);
	}

	public void depose() {

	}
	
	public int count() {
		return sessions.size();
	}
}

src/main/java/org/nlpcn/jcoder/controller/GroupAction.java
package org.nlpcn.jcoder.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.nlpcn.jcoder.domain.Task;
import org.nlpcn.jcoder.domain.UserGroup;
import org.nlpcn.jcoder.filter.AuthoritiesManager;
import org.nlpcn.jcoder.service.TaskService;
import org.nlpcn.jcoder.util.StaticValue;
import org.nlpcn.jcoder.util.dao.BasicDao;
import org.nutz.dao.Cnd;
import org.nutz.dao.Condition;
import org.nutz.ioc.loader.annotation.Inject;
import org.nutz.ioc.loader.annotation.IocBean;
import org.nutz.mvc.annotation.At;
import org.nutz.mvc.annotation.By;
import org.nutz.mvc.annotation.Fail;
import org.nutz.mvc.annotation.Filters;
import org.nutz.mvc.annotation.Ok;
import org.nutz.mvc.annotation.Param;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@IocBean
@Filters(@By(type = AuthoritiesManager.class, args = { "userType", "1", "/login.jsp" }))
public class GroupAction {

	private static final Logger LOG = LoggerFactory.getLogger(GroupAction.class);

	public BasicDao basicDao = StaticValue.systemDao;

	@Inject
	private TaskService taskService;

	@At("/auth/delUserGroup")
	@Ok("raw")
	@Fail("jsp:/fail.jsp")
	public boolean delUserGroup(@Param("id") long id) throws Exception {

		List<Task> tasksList = taskService.tasksList(id); // 从数据库中查出，不污染内存中的task

		for (Task task : tasksList) {
			taskService.delete(task);
			taskService.delByDB(task);
		}

		boolean flag = basicDao.delById(id, UserGroup.class);
		if (flag) {
			LOG.info("add userGroup which id:" + id);
		}
		return flag;
	}

	@At("/auth/updateUserGroup")
	@Ok("raw")
	public boolean updateUserGroup(@Param("groupId") Long groupId, @Param("auth") Integer auth, @Param("userId") Long userId) throws Exception {
		Condition con = Cnd.where("groupId", "=", groupId).and("userId", "=", userId);
		UserGroup userGroup = basicDao.findByCondition(UserGroup.class, con);
		if (userGroup == null) {
			userGroup = new UserGroup();
			userGroup.setUserId(userId);
			userGroup.setGroupId(groupId);
			userGroup.setCreateTime(new Date());
		}

		if (auth == 0) {
			basicDao.delById(userGroup.getId(), UserGroup.class);
		} else {
			userGroup.setAuth(auth);
			if (userGroup.getId() == null) {
				basicDao.save(userGroup);
			} else {
				basicDao.update(userGroup);
			}
		}

		return true;
	}

	/**
	 * 列出用户的所有权限
	 *
	 * @param userId
	 * @return
	 * @throws Exception
	 */
	@At("/auth/authUser")
	@Ok("json")
	public List<UserGroup> authUser(@Param("userId") long userId) throws Exception {
		return basicDao.search(UserGroup.class, Cnd.where("userId", "=", userId));
	}
}

src/main/webapp/jar_list.jsp
<%@page language="java" pageEncoding="UTF-8"%>
<%@include file="/common/taglibs.jsp"%>
<%@include file="common/common.jsp"%>

<!DOCTYPE html>
<html lang="cn">
<%@include file="header.jsp"%>
<link rel="stylesheet" type="text/css" href="${ctx }/webuploader/webuploader.css">
<script type="text/javascript" src="${ctx }/webuploader/webuploader.js"></script>

<!-- topbar ends -->
<div class="row">
	<!-- left menu starts -->
	<%@include file="left.jsp"%>
	<!-- left menu ends -->
	<div id="content" class="col-lg-10 col-sm-10">
		<c:forEach var="entry" items="${obj }">
		<div class="row">
			<div class="box col-md-12">
				<div class="box-inner">
					<div class="box-header well" data-original-title="">
						<h2>
							<i class="glyphicon glyphicon-user"></i>&nbsp;${entry.key }
						</h2>
						
						<div class="box-icon">
							<c:if test="${entry.key=='File' }">
								<a href="#"  id="update_begin" class="btn btn-round btn-default btn-success"><i class="glyphicon glyphicon-circle-arrow-up"></i></a>
							</c:if>
							<c:if test="${entry.key=='Maven' }">
								<a href="${ctx }/jar/maven" class="btn btn-round btn-default btn-success"><i class="glyphicon glyphicon-pencil"></i></a>
							</c:if>
		                </div>
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered">
							<thead>
								<tr>
									<th>Status</th>
									<th>Name</th>
									<th>Size</th>
									<th>Time</th>
									<th>Path</th>
									<c:if test="${entry.key=='File' }">
									<th>Edit</th>
									</c:if>
								</tr>
							</thead>
							<tbody>
									<c:forEach var="info" items="${entry.value}">
									<c:if test="${userType==1 || AUTH_MAP[task.groupId]==2}">
									<tr>
										<td class="center ">
											<c:if test="${info.status==0 }">
												<span class="label-success label label-default">Ok</span>
											</c:if>
											<c:if test="${info.status==1 }">
												<span class="label-default label">Unload</span>
											</c:if>
											<c:if test="${info.status==2 }">
												<span class="label-warning label label-default">Unrelease</span>
											</c:if>
											
										</td>
										<td>${info.file.name }</td>
										<td><fmt:formatNumber value="${info.file.length()/1024 }" type="currency" pattern="#0.00k"/></td>
										<td class="center">
											<fmt:formatDate value="${info.date }" type="both"/>
										</td>
										<td class="center"><input type="text" value="${info.file.path}" style="width: 100%; height: 100%"/></td>
										<c:if test="${entry.key=='File' }">
										<td class="center">
											<a class="btn btn-danger" href="${ctx }/jar/remove?path=${info.encodingPath}"><i class="glyphicon glyphicon-trash icon-white"></i> Delete </a>
										</td>
										</c:if>
									</tr>
									</c:if>
									</c:forEach>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!--/span-->
		</div>
		<!--/row-->
		</c:forEach>
	</div>
	
	<div class="modal fade" id="myModal" tabindex="-1" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Upload</h3>
				</div>
				<div class="modal-body">
					<div id="update_jar">upload Jars</div>
					<div id="update_jar_info"></div>
				</div>
				<div class="modal-footer">
					<a href="${ctx }/jar/list" class="btn btn-primary" >Ok</a>
				</div>
			</div>
		</div>
	</div>

	<%@include file="footer.jsp"%>
	
	
	<script type="text/javascript" src="${ctx }/webuploader/myupload.js"></script>
	<script type="text/javascript">
		var flag = true;
		$('#update_begin').click(function() {
			$('#dialog_message').text("shang");
			$('#myModal').modal('show');
			if(flag){
				flag = false ;
				for(var start = Date.now(); Date.now() - start <= 1000; ) { }
				createUploader("update_jar","${ctx}/jar/upload");
			}
		});
		
	</script>
	
	</body>
</html>

src/main/webapp/resource_list.jsp
<%@page language="java" pageEncoding="UTF-8"%>
<%@include file="/common/taglibs.jsp"%>
<%@include file="common/common.jsp"%>

<!DOCTYPE html>
<html lang="cn">
<%@include file="header.jsp"%>
<link rel="stylesheet" type="text/css" href="${ctx }/webuploader/webuploader.css">
<script type="text/javascript" src="${ctx }/webuploader/webuploader.js"></script>

<!-- topbar ends -->
<div class="row">
	<!-- left menu starts -->
	<%@include file="left.jsp"%>
	<!-- left menu ends -->
	<div id="content" class="col-lg-10 col-sm-10">
		<div class="row">
			<div class="box col-md-12">
				<div class="box-inner">
					<div class="box-header well" data-original-title="">
						<h2>
							<i class="glyphicon glyphicon-user"></i>&nbsp;Resource
						</h2>
						
						<div class="box-icon">
							<a href="#"  id="create_begin" class="btn btn-round btn-default btn-success"><i class="glyphicon glyphicon-folder-open"></i></a>
							<a href="#"  id="update_begin" class="btn btn-round btn-default btn-success"><i class="glyphicon glyphicon-circle-arrow-up"></i></a>
		                </div>
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered">
							<thead>
								<tr>
									<th>Name</th>
									<th>Size</th>
									<th>Modified time</th>
									<th>Path</th>
									<th>Operation</th>
								</tr>
							</thead>
							<tbody>
									<c:forEach var="info" items="${obj}">
									<tr>
										<td>
											<c:if test="${info.file.directory }">
												<i class="glyphicon blue glyphicon-inbox"></i> <a href="${ctx }/resource/list?path=${info.encodingPath}">${info.name }</a>
											</c:if>
											<c:if test="${!info.file.directory }">
												<i class="glyphicon blue glyphicon-file"></i> <a href="${ctx }/resource/down?path=${info.encodingPath}">${info.name }</a>
											</c:if>
										</td>
										<td><fmt:formatNumber value="${info.file.length()/1024 }" type="currency" pattern="#0.00k"/></td>
										<td class="center">
											<fmt:formatDate value="${info.date }" type="both"/>
										</td>
										<td class="center"><input type="text" value="${info.file.path}" style="width: 100%; height: 100%"/></td>
										<td class="center">
											<a class="btn btn-danger" href="${ctx }/resource/remove?path=${info.encodingPath}"><i class="glyphicon glyphicon-trash icon-white"></i> Delete </a>
										</td>
									</tr>
									</c:forEach>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!--/span-->
		</div>
		<!--/row-->
	</div>
	
	<div class="modal fade" id="myModal" tabindex="-1" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Upload</h3>
				</div>
				<div class="modal-body">
					<div id="update_file">Upload File</div>
					<div id="update_file_info"></div>
				</div>
				<div class="modal-footer">
					<a href="javascript:location.reload(true)" class="btn btn-primary" >确定</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="modal fade" id="createFile" tabindex="-1" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Create Dir</h3>
				</div>
				<div class="modal-body">
					<div id="update_file">Input Dir Name: <input type="text" class="form-control" placeholder="input folder name" id="createFileName"/></div>
				</div>
				<div class="modal-footer">
					<a id="create_folder_btn" href="#" class="btn btn-primary" >确定</a>
				</div>
			</div>
		</div>
	</div>

	<%@include file="footer.jsp"%>
	
	
	<script type="text/javascript" src="${ctx }/webuploader/myupload.js"></script>
	<script type="text/javascript">
	

		function getUrlParam(name) {
			var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
			var r = window.location.search.substr(1).match(reg);  //匹配目标参数
			if (r != null) return unescape(r[2]); return null; //返回参数值
       }
		
		var flag = true;
		$('#update_begin').click(function() {
			$('#myModal').modal('show');
			if(flag){
				flag = false ;
				for(var start = Date.now(); Date.now() - start <= 1000; ) { }
				
				var path = getUrlParam('path') ;
				
				if(path !=null){
					createUploader("update_file","${ctx}/resource/upload?path="+getUrlParam('path'));
				}else{
					createUploader("update_file","${ctx}/resource/upload");
				}
			}
		});
		
		$('#create_begin').click(function() {
			$('#createFile').modal('show');
		});
		
		
		$('#create_folder_btn').click(function(){
			
			var path = getUrlParam('path') ;
			
			if(path !=null){
				location.href = "${ctx}/resource/crate_folder?path="+getUrlParam('path')+"&floder="+$('#createFileName').val() ;
			}else{
				location.href = "${ctx}/resource/crate_folder?floder="+$('#createFileName').val() ;
			}
			
			
			
		})
		
	</script>
	
	</body>
</html>